### ISSUE TITLE
Css positioning

### ISSUE THREAD

**Issue by Feinminen** [RuefulMage/FD-Step2#19]
Position: absolute - нужно по-максимум избегать и использовать только в крайних случаях или в специально для этого предназначенных кейсах.
Например, отображение всплывающей подсказки можно сделать с помощью дефолтного атрибута title.
![image](https://user-images.githubusercontent.com/44312820/103079890-5b92e100-4607-11eb-9961-61a365d0a17f.png)
А ещё кастомные подсказки порой не полностью отображаются, из-за наложения z-index-ов (в карточках, когда тулпип заходит на button)

И ещё не совсем понял зачем такая реализация у slider-item:
![image](https://user-images.githubusercontent.com/44312820/103080038-9d238c00-4607-11eb-9d0d-d80cb28ab73f.png)

**Comment by RuefulMage** [comment]
![image](https://user-images.githubusercontent.com/53300730/109855954-f80ddb00-7c69-11eb-8b70-5200a4a9cd72.png)
Да, тут были лишние стили, которые никак не влияли на отображение и вот стили без лишнего. Вот сейчас здесь используется position:absolute, чтобы все фото были на одном месте и без позиционирования не работал hover при наведении на карточку
