### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by Feinminen** [RuefulMage/FD-Step2#27]
Сейчас что-то не так с фавайконами, т.к. они не отображаются :)
![image](https://user-images.githubusercontent.com/44312820/110238045-dc5c4a80-7f71-11eb-9745-e734b7a66df1.png)

**Comment by RuefulMage** [comment]
У меня все отображается( я кэш почистил, но все равно все работает нормально).
![image](https://user-images.githubusercontent.com/53300730/110517151-888d6500-811b-11eb-8c7e-a352d06df564.png) 
Я ошибки в консоли пофиксил, которые связаны с файлами favicons, может это решило проблему
