### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Feinminen** [RuefulMage/FD-Step2#31]
1. Не стоит использовать большие паддинги для элементов, т.к. это изменяет его размер.
![image](https://user-images.githubusercontent.com/44312820/111070447-5fe2e200-8504-11eb-8c03-a1a9d0c56713.png)
В данном случае же вообще нужно просто вертикальное выравнивание по центру, и можно использовать просто стнадратные средства флексбоксов для этого, если я всё правильно понимаю.

2. Всегда когда возможно использовать краткая форма записи css свойств:
![image](https://user-images.githubusercontent.com/44312820/111070511-adf7e580-8504-11eb-9c3a-db2aafc2d5cf.png)

3. Для font-family нужно явно добавить конкретный фолбэк шрифт, соответсвующий best-practises.

4. По бэстпрактисес двойные кавычки должны использоваться только в html (в основном как атрибуты), в css и JS-подобном коде должны быть одинарные кавычки.

**Comment by RuefulMage** [comment]
Насчет больших паддингов, там просто без падингов придется задавать фиксированную высоту элементу, но это  нежелательно по best practices
