### ISSUE TITLE
Внешний вид

### ISSUE THREAD

**Issue by kate-fsd** [RuefulMage/FD-Step2#4]
1. Страница home. У карточки добавь border-radius
![image](https://user-images.githubusercontent.com/66846004/91743182-16faba00-ebc0-11ea-9734-d93fe16266c6.png)

2. На карточке комнаты при наведении должна появляться тени и стрелочки. Без наведения их не должно быть

3. На дропдаунах при открытии у тебя добавляется пара лишних пикселей, видно как прыгает страница

4. Тут должен быть градиент
![image](https://user-images.githubusercontent.com/66846004/91746884-03525200-ebc6-11ea-839f-44d1ecadb2a3.png)

5. В инпутах у плейсхолдеров не тот шрифт. В заполненных тоже

6. Страница form-elements. Подписи default не того цвета. И проверь пожалуйста неактивные круглые кнопки, тоже вроде слишком бледные

7. Text field ниже чем в макете

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/94991001-cf819800-0588-11eb-8fe3-6f85fd07786c.png)

![image](https://user-images.githubusercontent.com/66846004/94991020-e3c59500-0588-11eb-87db-769ab6d5e7e9.png)

![image](https://user-images.githubusercontent.com/66846004/94991036-f50ea180-0588-11eb-9464-e040a4787670.png)

В некоторых местах элементы сильно жмутся друг к другу

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/94991106-63536400-0589-11eb-9412-e03ba16c9f3a.png)

1. Поправить инпуты дат 
2. Отступы
3. Число не должно разъезжаться на две строки. Добавь для него неразрывный пробел

**Comment by RuefulMage** [comment]
reopen

**Comment by kate-fsd** [comment]
Патрисия поплыла
![image](https://user-images.githubusercontent.com/66846004/96438599-30f36900-120f-11eb-8cd1-13dd64c508f1.png)

**Comment by kate-fsd** [comment]
Нужны отступы
![image](https://user-images.githubusercontent.com/66846004/96440176-44eb9a80-1210-11eb-9456-5c843058ecf0.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/96448532-34412180-121c-11eb-88be-53746619f859.png)
