### ISSUE TITLE
Код

### ISSUE THREAD

**Issue by kate-fsd** [RuefulMage/FD-Step2#7]
Лучше не дублировать код в if else 
![image](https://user-images.githubusercontent.com/66846004/93075454-7cee4380-f68e-11ea-9a9b-1f0eb656f9a7.png)

**Comment by kate-fsd** [comment]
values[0] + '₽ - ' + values[1] +'₽'
лучше так ``${values[0]}₽ - ${values[1]}₽``

**Comment by kate-fsd** [comment]
https://github.com/leonidlebedev/javascript-airbnb#variables--unary-increment-decrement

**Comment by kate-fsd** [comment]
Есть места где название класса с js- не совпадает с основным. Например тут:
button.dropdown__increase.js-dropdown-increase
в стандартах https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#jquery--caching

**Comment by RuefulMage** [comment]
Ошибки с инкрементами, дикрементами и кавычками исправил, когда исправлял ошибки линтера

**Comment by kate-fsd** [comment]
> Есть места где название класса с js- не совпадает с основным

![image](https://user-images.githubusercontent.com/66846004/93921855-d0f5c980-fd19-11ea-91f8-b0eddb7e3e1c.png)

**Comment by RuefulMage** [comment]
А я могу оставить такие случаи? То есть тут стили для обоих кнопок одинаковые, но поведение разное. Или мне нужно для каждой кнопки сделать еще класс apartment-description-card__prev-button и  apartment-description-card__next-button
![image](https://user-images.githubusercontent.com/53300730/94437668-bd79b100-01a6-11eb-9bf0-2d7cc759e460.png)

**Comment by kate-fsd** [comment]
Здесь можно не дублировать
![image](https://user-images.githubusercontent.com/66846004/94990935-466a6100-0588-11eb-9796-24dd95a78518.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/96441557-62b9ff00-1212-11eb-9675-513633ff3d83.png)

лучше each .. in

**Comment by kate-fsd** [comment]
Можно без переменной i
+apartment-description-card(card)
