### ISSUE TITLE
Компоненты

### ISSUE THREAD

**Issue by kate-fsd** [RuefulMage/FD-Step2#8]
Сейчас у тебя каждый слайдер вызывается с такими параметрами
createRangeSlider(slidersList[i], [5000, 10000], 500, 15000);
Сделай так, чтобы этот компонент был универсальным. Передавай необходимые данные для js в data-атрибутах.

**Comment by kate-fsd** [comment]
В pie-chart
![image](https://user-images.githubusercontent.com/66846004/93079050-2be14e00-f694-11ea-8f5b-b6a41cf01967.png)
Представь, что у тебя на этом сайте есть возможность поменять язык. Весь текст должен приходить сверху. Данные должны находиться на уровне страниц, можно в отдельных json файлах.
Еще в пончике добавь возможность передать более четырех значений

**Comment by kate-fsd** [comment]
> Еще в пончике добавь возможность передать более четырех значений

Сейчас принимает четыре

**Comment by kate-fsd** [comment]
bullet и bullet-list
bullet - 1 пункт в списке, в отрыве от самого списка не существует (по крайней мере судя по твоему коду, тег li). Тем более он очень простой. Лучше сделать блок bullet-list, а один пункт - его элементом

**Comment by RuefulMage** [comment]
Примеры разного количества секторов у pie chart:
![image](https://user-images.githubusercontent.com/53300730/94675516-87613c00-0322-11eb-954b-1b48b0d3f32d.png)
![image](https://user-images.githubusercontent.com/53300730/94675549-91833a80-0322-11eb-8dbb-475ef3013cb2.png)
![image](https://user-images.githubusercontent.com/53300730/94675572-9a740c00-0322-11eb-900d-758b739bdd94.png)
![image](https://user-images.githubusercontent.com/53300730/94675600-a52ea100-0322-11eb-85c4-b1808b7e7d00.png)
![image](https://user-images.githubusercontent.com/53300730/94675621-ad86dc00-0322-11eb-926a-4ca1a8821ecf.png)
